name: Deployment Exercise 2
on: push
jobs:
  lint:
    runs-on: macos-12
    steps:
      - name: Get code
        uses: actions/checkout@v3 #When you want to use action
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint
  test:
    runs-on: macos-12
    steps:
      - name: Get code
        uses: actions/checkout@v3 #When you want to use action
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint
      - name: Test code
        run: npm run test
  deploy:
    runs-on: macos-12
    steps:
      - name: Get code
        uses: actions/checkout@v3 #When you want to use action
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo " Deploying....." 
